exit_polling/poller_phx/lib/poller_phx_web/router.ex
defmodule PollerPhxWeb.Router do
  use PollerPhxWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PollerPhxWeb.Plugs.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PollerPhxWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/auth", PollerPhxWeb do
    pipe_through :browser

    get "/login", AuthController, :new
    post "/login", AuthController, :create
    delete "/logout", AuthController, :delete
  end

  scope "/districts", PollerPhxWeb do
    pipe_through [:browser, :valid_user, :admin_user]

    resources "/", DistrictController, except: [:show]
    resources "/:district_id/questions", QuestionController, except: [:show]
    resources "/:district_id/questions/:question_id/choices", ChoiceController, except: [:show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", PollerPhxWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PollerPhxWeb.Telemetry
    end
  end
end

exit_polling/poller_phx/lib/poller_phx_web/controllers/district_controller.ex
defmodule PollerPhxWeb.DistrictController do
  use PollerPhxWeb, :controller

  alias PollerDal.Districts
  alias PollerDal.Districts.District

  def index(conn, _params) do
    districts = Districts.list_districts()
    render(conn, "index.html", districts: districts)
  end

  def new(conn, _params) do
    changeset = Districts.change_district(%District{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"district" => district_params}) do
    case Districts.create_district(district_params) do
      {:ok, _district} ->
        conn
        |> put_flash(:info, "District created successfully.")
        |> redirect(to: Routes.district_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> render("new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}) do
    district = Districts.get_district!(id)
    changeset = Districts.change_district(district)

    conn
    |> render("edit.html", district: district, changeset: changeset)
  end

  def update(conn, %{"id" => id, "district" => district_params}) do
    district = Districts.get_district!(id)

    case Districts.update_district(district, district_params) do
      {:ok, _district} ->
        conn
        |> put_flash(:info, "District updated successfully.")
        |> redirect(to: Routes.district_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> render("edit.html", district: district, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    district = Districts.get_district!(id)
    {:ok, _district} = Districts.delete_district(district)

    conn
    |> put_flash(:info, "District delete successfully.")
    |> redirect(to: Routes.district_path(conn, :index))
  end
end

exit_polling/poller_phx/lib/poller_phx_web/views/district_view.ex
defmodule PollerPhxWeb.DistrictView do
  use PollerPhxWeb, :view
end

exit_polling/poller_phx/lib/poller_phx_web/templates/district/edit.html.eex
<h1>Edit District</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.district_path(@conn, :update, @district)) %>

exit_polling/poller_phx/lib/poller_phx_web/templates/district/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="error">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <div>
    <%= submit "Save", class: "btn" %>
    <%= link "Cancel", to: Routes.district_path(@conn, :index), class: "btn-white" %>
  </div>
<% end %>

exit_polling/poller_phx/lib/poller_phx_web/templates/district/index.html.eex
<h1>Districts</h1>

<table>
  <thead>
    <tr>
      <th colspan="2">Name</th>
    </tr>
  </thead>
  <tbody>
    <%= for district <- @districts do %>
      <tr>
        <td><%= district.name %></td>
        <td>
          <%= link to: Routes.question_path(@conn, :index, district.id) do %>
            <i class="fas fa-question"></i>
          <% end %>
          <%= link to: Routes.district_path(@conn, :edit, district.id) do %>
            <i class="far fa-edit"></i>
          <% end %>
          <%= link to: Routes.district_path(@conn, :delete, district.id),
                method: :delete,
                data: [confirm: "Are you sure?"] do %>
              <i class="fas fa-trash"></i>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
  <%= link "New District", to: Routes.district_path(@conn, :new), class: "btn" %>
</div>

exit_polling/poller_phx/lib/poller_phx_web/templates/district/new.html.eex
<h1>New District</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.district_path(@conn, :create)) %>